spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_stack?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 724888
    driver-class-name: com.mysql.cj.jdbc.Driver