spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_stack?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 724888
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 7001  #该 Module 的端口号

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称，

  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版服务注册中心